[project]
name = "fishing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.47.2",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "plotly>=5.22.0",
    "seaborn>=0.13.0",
]
